apiVersion: v1
kind: Service
metadata:
  name: gis-backend
  labels:
    app: gis-backend
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: gis-backend
